# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  graphqlwebapi:
    image: graphqlwebapi
    container_name: 'graphqlwebapi-container'
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5001:5000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:5.0.3
    container_name: 'mongodb-container'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=projectsdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - mongodb_server_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - 29017-29019:27017-27019
volumes:
  mongodb_server_data: